<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
    <!-- Package identity -->
		<PackageId>STSS.Core.Identity.Dtos</PackageId>
		<Description>Shared DTOs for STSS.Core.Identity orchestration and transport.</Description>
		<Title>STSS.Core.Identity DTO Contracts</Title>
		<PackageTags>core,identity,dtos,contracts,strutton,StruttonTechnologies</PackageTags>

    <!-- Versioning -->
    <VersionPrefix>1.0.0</VersionPrefix>
    <VersionSuffix>alpha</VersionSuffix>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="PersonLinking\" />
	</ItemGroup>

</Project>
