<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Package identity -->
		<PackageId>StruttonTechnologies.Core.Repositories.Contracts</PackageId>
		<Description>
			Contract interfaces and abstractions for repository patterns in ST.Core —
			supports modular data access and persistence strategies.
		</Description>
		<PackageTags>
			core; infrastructure; repository; repositories; contracts; interfaces;
			strutton; struttontechnologies
		</PackageTags>

		<!-- Versioning -->
		<VersionPrefix>1.0.0</VersionPrefix>
		<VersionSuffix>alpha</VersionSuffix>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Domains\StruttonTechnologies.Core.Domain\StruttonTechnologies.Core.Domain.csproj" />
	</ItemGroup>

</Project>
