<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>StruttonTechnologies.Core.Identity.API.Contracts</AssemblyName>
    <RootNamespace>StruttonTechnologies.Core.Identity.API.Contracts</RootNamespace>

    <PackageId>StruttonTechnologies.Core.Identity.API.Contracts</PackageId>

    <Title>Identity API Contracts for ST.Core</Title>

    <Description>
      API contract interfaces, request models, response models, and endpoint abstractions
      for the Strutton Technologies Core Identity capability.
    </Description>

    <PackageTags>
      core;CoreCapabilities;identity;authentication;authorization;jwt;
      api;contracts;dto;requests;responses;
      architecture;clean-architecture;modular;modular-architecture;
      dotnet;strutton;struttontechnologies
    </PackageTags>

    <VersionPrefix>1.0.0</VersionPrefix>
    <VersionSuffix>alpha</VersionSuffix>

    <IsPackable>true</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

</Project>