<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>StruttonTechnologies.Core.Orchestration.Contracts</PackageId>
    <Title>Orchestration Contracts for ST.Core</Title>
    <Description>
			Contract interfaces and abstractions for orchestration services in StruttonTechnologies.Core.
		</Description>
    <PackageTags>core; contracts; interfaces; orchestration; services; strutton; struttontechnologies</PackageTags>
    <VersionPrefix>1.0.0</VersionPrefix>
    <VersionSuffix>alpha</VersionSuffix>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Domains\StruttonTechnologies.Core.Domain\StruttonTechnologies.Core.Domain.csproj" />
  </ItemGroup>
</Project>